/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _Migrations {
  id: Generated<Int8>;
  name: string;
  runAt: Generated<Timestamp | null>;
}

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface BannedCustomers {
  bannedAt: Generated<Timestamp>;
  bannedUntil: Timestamp | null;
  createdAt: Generated<Timestamp>;
  customerPhone: string;
  id: Generated<string>;
  organizationId: string;
  reason: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Bookings {
  createdAt: Generated<Timestamp>;
  customerName: string;
  customerPhone: string;
  endTime: Timestamp;
  id: Generated<string>;
  memberId: string | null;
  notes: string | null;
  organizationId: string;
  priceAtBooking: number;
  serviceId: string | null;
  startTime: Timestamp;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Invitations {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Members {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  organizationId: string;
  role: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface MemberScheduleOverrides {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  endTime: string | null;
  id: Generated<string>;
  memberId: string;
  reason: string | null;
  startTime: string | null;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface MemberServices {
  memberId: string;
  serviceId: string;
}

export interface MemberWeeklySchedules {
  createdAt: Generated<Timestamp>;
  dayOfWeek: number;
  endTime: string;
  id: Generated<string>;
  memberId: string;
  startTime: string;
  updatedAt: Generated<Timestamp>;
}

export interface Organizations {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface Services {
  createdAt: Generated<Timestamp>;
  description: string | null;
  durationMin: number;
  id: Generated<string>;
  isActive: Generated<boolean | null>;
  name: string;
  organizationId: string;
  priceCents: number;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  _Migrations: _Migrations;
  accounts: Accounts;
  bannedCustomers: BannedCustomers;
  bookings: Bookings;
  invitations: Invitations;
  members: Members;
  memberScheduleOverrides: MemberScheduleOverrides;
  memberServices: MemberServices;
  memberWeeklySchedules: MemberWeeklySchedules;
  organizations: Organizations;
  services: Services;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
